{% set name = "Orange3-Geo" %}
{% set version = "0.2.2" %}
{% set sha256 = "4b2b2099314157706f6ef1f1c79e2158703e8b76fb4f16f0d655af768b0ca948" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - orange3
    - scikit-learn
    - pandas
    - scipy >=0.17
    - shapely
    - simplejson

test:
  imports:
    - orangecontrib.geo

about:
  home: http://github.com/biolab/orange3-geo
  license: GPL-3.0
  license_family: GPL
  summary: 'Orange add-on for dealing with geography and geo-location'
  dev_url: http://github.com/biolab/orange3-geo

extra:
  recipe-maintainers:
    - kernc
    - astaric
