appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eERYOBMk+093LMxWgnQRf6Ieied57oqfn5/pvC9PXF2qpaGKtYwHaeyd6lf+AYeTP8AGFLH9fij0vCPmlotPotRB9/wdHF458GZEQ2yxhNXKkTHIY/6URM+l0n4AijiC8WOZtl0httn5gjLv0Rpojxdhx0TAH7LJn3hHSngTavHdfVZ/7YzhY84JLaouCbE25RqJuAlIBbBuMt+uMF0oJSEPs8TLvofsckyN24lNMa+kKcOMe2Nru3TgIvrWLsf61wakIEk9zLoC1FoUctkaA9ci1UelShBmUbV8IETiWTZCH2ryicqiwKaS9+sG2y4rA/o0t1MKgQOChdDG9Ge5sUdOPiL3dC1p5o7n/Y/fMd1jXlcW+G0J+5TBCAvdFOWoEjd6mVw/4tAOkf4B2VhD1HEMdxjxgXboxfu/RDl8BrI2LLIE0Tvn1X8KM9cxwAdupd1Ng6blLRvEltD/htbPu5i9br3pxLO7uaI/YAmP9x8Mvsj4NCAdaKrLm3EQiau7mNkh9hyvb2k+c0gHhaXwhd7cXBbyHuiReOPvhAEBL/iBK8rsLur6hafx9HIo8caf09OkwxaPdpA713ZR52qCFjOw/8JJ/DhOtE/XWY2XxZd/nQZptVVEeVLjlHLVtTCmNsBFd39V8VuMnJm8iXxPrwbYpVRs1NB1DrAs1LHfKj0=}
