travis:
  secure:
    BINSTAR_TOKEN: j65/lkrj8GWmdOXp8SkKl8t31rXKOxY+gEANfsxNoB4Ddtjx4byCspbswrlj1iOUvHEZhSt4MobF+lRV/h+l2OxyK/f5O69tdk7gJC3j7cUv2fUnS9AriZI6p2QjyX4u7IQnwQ9cf6EpBsTeh20CsS9BcQDTgilkJH2wkygC7WQRyAj0gqImofqBn1h6m8Awko43sz5fJAU9ZKKN+oO83DLHhs8Ea/bpdHbPvyzYjpVqLnqG2lkTK4LPkQvAb6/Xy39tIX6bAcUMhSv3B3Q5wHPFU/mbzLt0ag/tTbXMDdbwlD+45LEA7SBc4deMI43qEaOI2eSA7px16TuhkTttK+07tGpbgsLGiRc8YD1KPiARVa5gntVodjg0hGMtxAQ7UJrf+5ToTDpQe1A/lNuG2/51e7164AQj6pBwVixR8mCpUO0aQh1nOEtZ+e0VATeLJy1RpVDBB9ns8kYauXhysVsSFDYBU253BjJiMaeflIJj3ee7/3lDI1Bht5Bwi61k4wARF0cJPHUQPIKAmsw6HQdARP7exQsZkhE0/RdmQomiCeW/nPM3gv+MK93KOf76dOQK+9sjXUvQ+lh1q1V9mO6cNzB6iV0NGMyMkCdUssHs9lwp3x3xLUb/KyxyvZJAhu5hRHseCqXqf61bvEc7+DAjq2kHO9wKf8NqkaHoL9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
